from django.urls import path
from .views import *

urlpatterns = [
    path('insert', insert, name='insert'),
    path('insert2', insert2, name='insert2'),
    path('', show, name='show'),
    path('show', show, name='show'),
    path('fail', show, name='fail'),
    path('show2', show2, name='show2'),
    path('show3', show3, name='show3'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', delete, name='delete'),
    path('tag1/', tag1, name='tag1'),
    path('tag2/', tag2, name='tag2'),
    path('tag3/', tag3, name='tag3'),
    path('tag4/', tag4, name='tag4'),
    path('tag5/', tag5, name='tag5'),
    path('tag6/', tag6, name='tag6'),
    path('tag7/', tag7, name='tag7'),
    path('tag11/', tag11, name='tag11'),
    path('tag12/', tag12, name='tag12'),
    path('tag13/', tag13, name='tag13'),
    path('tag14/', tag14, name='tag14'),
    path('tag15/', tag15, name='tag15'),
    path('tag16/', tag16, name='tag16'),
    path('tag17/', tag17, name='tag17'),
    path('tag18/', tag18, name='tag18'),
    path('tag19/', tag19, name='tag19'),
    path('tag20/', tag20, name='tag20'),
    path('tag21/', tag21, name='tag21'),
    path('MLS/', MLS, name='MLS'),
    path('AppleTV/', AppleTV, name='AppleTV'),
    path('MLS2/', MLS2, name='MLS2'),
    path('AppleTV2/', AppleTV2, name='AppleTV2'),
]
